In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
pd.options.display.max_columns = 200
pd.options.display.max_rows = 170

# Overview of Data

In [3]:
df = pd.read_csv("data/4_year/2019GraduationRates.csv", index_col="UnitID")

In [4]:
df[df.index.duplicated()]

Empty DataFrame
Columns: [Institution Name, City location of institution (HD2019), Grand total (S2019_IS  All instructional staff), Grand total men (S2019_IS  All instructional staff), Grand total women (S2019_IS  All instructional staff), American Indian or Alaska Native total (S2019_IS  All instructional staff), American Indian or Alaska Native men (S2019_IS  All instructional staff), American Indian or Alaska Native women (S2019_IS  All instructional staff), Asian total (S2019_IS  All instructional staff), Asian men (S2019_IS  All instructional staff), Asian women (S2019_IS  All instructional staff), Black or African American total (S2019_IS  All instructional staff), Black or African American men (S2019_IS  All instructional staff), Black or African American women (S2019_IS  All instructional staff), Hispanic or Latino total (S2019_IS  All instructional staff), Hispanic or Latino men (S2019_IS  All instructional staff), Hispanic or Latino women (S2019_IS  All instructional staff), Native Hawaiian or Other Pacific Islander total (S2019_IS  All instructional staff), Native Hawaiian or Other Pacific Islander men (S2019_IS  All instructional staff), Native Hawaiian or Other Pacific Islander women (S2019_IS  All instructional staff), White total (S2019_IS  All instructional staff), White men (S2019_IS  All instructional staff), White women (S2019_IS  All instructional staff), Two or more races total (S2019_IS  All instructional staff), Two or more races men (S2019_IS  All instructional staff), Two or more races women (S2019_IS  All instructional staff), Race/ethnicity unknown total (S2019_IS  All instructional staff), Race/ethnicity unknown men (S2019_IS  All instructional staff), Race/ethnicity unknown women (S2019_IS  All instructional staff), Nonresident alien total (S2019_IS  All instructional staff), Nonresident alien men (S2019_IS  All instructional staff), Nonresident alien women (S2019_IS  All instructional staff), Graduation rate  total cohort (DRVGR2019), Graduation rate  men (DRVGR2019), Graduation rate  women (DRVGR2019), Graduation rate  American Indian or Alaska Native (DRVGR2019), Graduation rate  Asian/Native Hawaiian/Other Pacific Islander (DRVGR2019), Graduation rate  Asian (DRVGR2019), Graduation rate  Native Hawaiian or Other Pacific Islander (DRVGR2019), Graduation rate  Black  non-Hispanic (DRVGR2019), Graduation rate  Hispanic (DRVGR2019), Graduation rate  White  non-Hispanic (DRVGR2019), Graduation rate  two or more races (DRVGR2019), Graduation rate  Race/ethnicity unknown (DRVGR2019), Graduation rate  Nonresident alien (DRVGR2019), Transfer-out rate  total cohort (DRVGR2019), Percent of full-time first-time undergraduates awarded any financial aid (SFA1819), Percent of full-time first-time undergraduates awarded federal  state  local or institutional grant aid (SFA1819), Core revenues  total dollars (GASB) (DRVF2019), Tuition and fees as a percent of core revenues (GASB) (DRVF2019), State appropriations as percent of core revenues  (GASB) (DRVF2019), Local appropriations as a percent of core revenues (GASB) (DRVF2019), Government grants and contracts as a percent of core revenues (GASB) (DRVF2019), Private gifts  grants  and contracts as a percent of core revenues (GASB) (DRVF2019), Investment return as a percent of core revenues (GASB) (DRVF2019), Other revenues as a percent of core revenues (GASB) (DRVF2019), Core revenues  total dollars (FASB) (DRVF2019), Tuition and fees as a percent of core revenues (FASB) (DRVF2019), Government grants and contracts as a percent of core revenues (FASB) (DRVF2019), Private gifts  grants  contracts/contributions from affiliated entities as a percent of core revenues (FASB) (DRVF2019), Investment return as a percent of core revenues (FASB) (DRVF2019), Other revenues as a percent of core revenues (FASB) (DRVF2019), Core revenues  total dollars (for-profit institutions) (DRVF2019), Tuition and fees as a percent of core revenues (for-profit institutions) (DRVF2019), Government grants and contracts as a percent of core revenues (for-profit institutions) (DRVF2019), Private gifts  grants  contracts as a percent of core revenues (for-profit institutions) (DRVF2019), Investment return as a percent of core revenues (for-profit institutions) (DRVF2019), Sales and services of educational activities as a percent of core revenues (for-profit institutions) (DRVF2019), Other revenues as a percent of core revenues (for-profit institutions) (DRVF2019), Core expenses  total dollars (GASB) (DRVF2019), Instruction expenses as a percent of total core expenses (GASB) (DRVF2019), Research expenses as a percent of total core expenses (GASB) (DRVF2019), Public service expenses as a percent of total core expenses (GASB) (DRVF2019), Academic support expenses as a percent of total core expenses (GASB) (DRVF2019), Student service expenses as a percent of total core expenses (GASB) (DRVF2019), Institutional support expenses as a percent of total core expenses (GASB) (DRVF2019), Other core expenses as a percent of total core expenses (GASB) (DRVF2019), Core expenses  total dollars (FASB) (DRVF2019), Instruction expenses as a percent of total core expenses (FASB) (DRVF2019), Research expenses as a percent of total core expenses (FASB) (DRVF2019), Public service expenses as a percent of total core expenses (FASB) (DRVF2019), Academic support expenses as a percent of total core expenses (FASB) (DRVF2019), Student service expenses as a percent of total core expenses (FASB) (DRVF2019), Institutional support expenses as a percent of total core expenses (FASB) (DRVF2019), Other core expenses as a percent of total core expenses (FASB) (DRVF2019), Core expenses  total dollars (for-profit institutons) (DRVF2019), Instruction expenses as a percent of total core expenses (for-profit institutions) (DRVF2019), Research expenses as a percent of total core expenses (for-profit institutions) (DRVF2019), Public service expenses as a percent of total core expenses (for-profit institutions) (DRVF2019), Academic support expenses as a percent of total core expenses (for-profit institutions) (DRVF2019), Student service expenses as a percent of total core expenses (for-profit institutions) (DRVF2019), Institutional support expenses as a percent of total core expenses (for-profit institutions) (DRVF2019), Other core expenses as a percent of total  core expenses (for-profit institutions) (DRVF2019), Carnegie Classification 2018: Size and Setting (HD2018), Carnegie Classification 2018: Enrollment Profile (HD2018), Carnegie Classification 2018: Basic (HD2018), State abbreviation (HD2018), Institution size category (HD2018), Sector of institution (HD2018), Historically Black College or University (HD2018), ...]
Index: []

In [5]:
df.drop(
    df.filter(regex="Unnamed").columns[0],
    axis=1, 
    inplace=True
)

In [6]:
df.describe()

,Grand total (S2019_IS All instructional staff),Grand total men (S2019_IS All instructional staff),Grand total women (S2019_IS All instructional staff),American Indian or Alaska Native total (S2019_IS All instructional staff),American Indian or Alaska Native men (S2019_IS All instructional staff),American Indian or Alaska Native women (S2019_IS All instructional staff),Asian total (S2019_IS All instructional staff),Asian men (S2019_IS All instructional staff),Asian women (S2019_IS All instructional staff),Black or African American total (S2019_IS All instructional staff),Black or African American men (S2019_IS All instructional staff),Black or African American women (S2019_IS All instructional staff),Hispanic or Latino total (S2019_IS All instructional staff),Hispanic or Latino men (S2019_IS All instructional staff),Hispanic or Latino women (S2019_IS All instructional staff),Native Hawaiian or Other Pacific Islander total (S2019_IS All instructional staff),Native Hawaiian or Other Pacific Islander men (S2019_IS All instructional staff),Native Hawaiian or Other Pacific Islander women (S2019_IS All instructional staff),White total (S2019_IS All instructional staff),White men (S2019_IS All instructional staff),White women (S2019_IS All instructional staff),Two or more races total (S2019_IS All instructional staff),Two or more races men (S2019_IS All instructional staff),Two or more races women (S2019_IS All instructional staff),Race/ethnicity unknown total (S2019_IS All instructional staff),Race/ethnicity unknown men (S2019_IS All instructional staff),Race/ethnicity unknown women (S2019_IS All instructional staff),Nonresident alien total (S2019_IS All instructional staff),Nonresident alien men (S2019_IS All instructional staff),Nonresident alien women (S2019_IS All instructional staff),Graduation rate total cohort (DRVGR2019),Graduation rate men (DRVGR2019),Graduation rate women (DRVGR2019),Graduation rate American Indian or Alaska Native (DRVGR2019),Graduation rate Asian/Native Hawaiian/Other Pacific Islander (DRVGR2019),Graduation rate Asian (DRVGR2019),Graduation rate Native Hawaiian or Other Pacific Islander (DRVGR2019),Graduation rate Black non-Hispanic (DRVGR2019),Graduation rate Hispanic (DRVGR2019),Graduation rate White non-Hispanic (DRVGR2019),Graduation rate two or more races (DRVGR2019),Graduation rate Race/ethnicity unknown (DRVGR2019),Graduation rate Nonresident alien (DRVGR2019),Transfer-out rate total cohort (DRVGR2019),Percent of full-time first-time undergraduates awarded any financial aid (SFA1819),Percent of full-time first-time undergraduates awarded federal state local or institutional grant aid (SFA1819),Core revenues total dollars (GASB) (DRVF2019),Tuition and fees as a percent of core revenues (GASB) (DRVF2019),State appropriations as percent of core revenues (GASB) (DRVF2019),Local appropriations as a percent of core revenues (GASB) (DRVF2019),Government grants and contracts as a percent of core revenues (GASB) (DRVF2019),Private gifts grants and contracts as a percent of core revenues (GASB) (DRVF2019),Investment return as a percent of core revenues (GASB) (DRVF2019),Other revenues as a percent of core revenues (GASB) (DRVF2019),Core revenues total dollars (FASB) (DRVF2019),Tuition and fees as a percent of core revenues (FASB) (DRVF2019),Government grants and contracts as a percent of core revenues (FASB) (DRVF2019),Private gifts grants contracts/contributions from affiliated entities as a percent of core revenues (FASB) (DRVF2019),Investment return as a percent of core revenues (FASB) (DRVF2019),Other revenues as a percent of core revenues (FASB) (DRVF2019),Core revenues total dollars (for-profit institutions) (DRVF2019),Tuition and fees as a percent of core revenues (for-profit institutions) (DRVF2019),Government grants and contracts as a percent of core revenues (for-profit institutions) (DRVF2019),Private gifts grants contracts as a percent of core revenues (for-profit institutions) (DRVF2019),Investment return as a percent of core revenues (for-profit institutions) (DRVF2019),Sales and services of educational activities as a percent of core revenues (for-profit institutions) (DRVF2019),Other revenues as a percent of core revenues (for-profit institutions) (DRVF2019),Core expenses total dollars (GASB) (DRVF2019),Instruction expenses as a percent of total core expenses (GASB) (DRVF2019),Research expenses as a percent of total core expenses (GASB) (DRVF2019),Public service expenses as a percent of total core expenses (GASB) (DRVF2019),Academic support expenses as a percent of total core expenses (GASB) (DRVF2019),Student service expenses as a percent of total core expenses (GASB) (DRVF2019),Institutional support expenses as a percent of total core expenses (GASB) (DRVF2019),Other core expenses as a percent of total core expenses (GASB) (DRVF2019),Core expenses total dollars (FASB) (DRVF2019),Instruction expenses as a percent of total core expenses (FASB) (DRVF2019),Research expenses as a percent of total core expenses (FASB) (DRVF2019),Public service expenses as a percent of total core expenses (FASB) (DRVF2019),Academic support expenses as a percent of total core expenses (FASB) (DRVF2019),Student service expenses as a percent of total core expenses (FASB) (DRVF2019),Institutional support expenses as a percent of total core expenses (FASB) (DRVF2019),Other core expenses as a percent of total core expenses (FASB) (DRVF2019),Core expenses total dollars (for-profit institutons) (DRVF2019),Instruction expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Research expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Public service expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Academic support expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Student service expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Institutional support expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Other core expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Carnegie Classification 2018: Size and Setting (HD2018),Carnegie Classification 2018: Enrollment Profile (HD2018),Carnegie Classification 2018: Basic (HD2018),Institution size category (HD2018),Sector of institution (HD2018),Historically Black College or University (HD2018),Student-to-faculty ratio (EF2019D),Parent/child indicator - Finance (FLAGS2019),Total price for in-district students living on campus 2014-15 (DRVIC2014),Total price for in-state students living on campus 2014-15 (DRVIC2014),Total price for out-of-state students living on campus 2014-15 (DRVIC2014),Total price for in-district students living off campus (not with family) 2014-15 (DRVIC2014),Total price for in-state students living off campus (not with family) 2014-15 (DRVIC2014),Total price for out-of-state students living off campus (not with family) 2014-15 (DRVIC2014),Total price for in-district students living off campus (with family) 2014-15 (DRVIC2014),Total price for in-state students living off campus (with family) 2014-15 (DRVIC2014),Total price for out-of-state students living off campus (with family) 2014-15 (DRVIC2014),SAT Critical Reading 75th percentile score (ADM2014_RV),SAT Writing 75th percentile score (ADM2014_RV),SAT Math 75th percentile score (ADM2014_RV),ACT Composite 75th percentile score (ADM2014_RV),ACT English 75th percentile score (ADM2014_RV),ACT Math 75th percentile score (ADM2014_RV),ACT Writing 75th percentile score (ADM2014_RV),Total men (EF2014B_RV Undergraduate Age under 25 total),Total women (EF2014B_RV Undergraduate Age under 25 total),Grand total (EF2014B_RV Undergraduate Age under 25 total),Total men (EF2014B_RV Undergraduate Age 25 and over total),Total women (EF2014B_RV Undergraduate Age 25 and over total),Grand total (EF2014B_RV Undergraduate Age 25 and over total),Percent of total enrollment that are White (DRVEF2014_RV),Percent of total enrollment that are Black or African American (DRVEF2014_RV),Percent of total enrollment that are Hispanic/Latino (DRVEF2014_RV),Percent of total enrollment that are Asian/Native Hawaiian/Pacific Islander (DRVEF2014_RV),Percent of total enrollment that are American Indian or Alaska Native (DRVEF2014_RV),Percent of total enrollment that are Race/ethnicity unknown (DRVEF2014_RV),Percent of total enrollment that are Nonresident Alien (DRVEF2014_RV),Percent of total enrollment that are women (DRVEF2014_RV),Percent of total enrollment that are two or more races (DRVEF2014_RV),Percent of total enrollment that are Asian (DRVEF2014_RV),Percent of total enrollment that are Native Hawaiian or Other Pacific Islander (DRVEF2014_RV)
count,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2466.000000,2315.000000,2248.000000,2208.000000,1405.000000,1829.000000,1777.000000,943.000000,2027.000000,2075.000000,2204.000000,1720.000000,1692.000000,1572.000000,1385.000000,2321.000000,2321.000000,7.660000e+02,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,1.690000e+03,1689.000000,1689.000000,1689.000000,1689.000000,1689.000000,3.580000e+02,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,7.660000e+02,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,1.690000e+03,1690.000000,1690.000000,1690.000000,1690.000000,1690.000000,1690.000000,1690.000000,3.580000e+02,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,2791.000000,2791.000000,2791.000000,2791.000000,2791.000000,2791.000000,2493.000000,2825.000000,1692.000000,1692.000000,1692.000000,2160.000000,2160.000000,2160.000000,2170.000000,2170.000000,2170.000000,1166.000000,718.000000,1179.000000,1224.000000,1079.000000,1081.000000,297.000000,1357.000000,1357.000000,1357.000000,1354.000000,1354.000000,1354.000000,2676.000000,2676.000000,2676.000000,2676.000000,2676.000000,2676.000000,2676.000000,2676.000000,2676.000000,2676.000000,2676.000000
mean,259.922952,139.502839,120.420114,0.969992,0.467153,0.502839,28.109489,16.305353,11.804136,14.141119,6.178427,7.962693,14.710057,7.359286,7.350770,0.453771,0.228710,0.225061,180.768451,97.263990,83.504461,2.601784,1.193431,1.408354,8.178832,4.347526,3.831306,9.989457,6.158962,3.830495,51.535205,47.922598,54.874547,41.953737,57.539639,59.046708,48.973489,41.239763,47.868434,54.559891,48.453488,50.320922,58.502545,23.941516,88.905213,84.039638,3.292445e+08,29.030026,29.013055,1.976501,22.265013,4.142298,1.737598,11.812010,1.146889e+08,63.142096,4.917111,19.590882,7.033156,5.300770,3.208575e+07,94.053073,1.879888,0.053073,0.391061,1.558659,2.022346,3.106305e+08,41.157963,6.074413,3.701044,10.639687,10.308094,13.740209,14.344648,1.022910e+08,39.509467,2.011834,1.117751,10.633728,17.081657,25.259172,4.394675,2.734069e+07,30.368715,0.120112,0.226257,13.784916,13.284916,33.798883,8.477654,10.616267,3.625582,20.482981,2.077033,1.890720,1.968112,14.211793,-1.440708,34289.555556,34298.073877,37721.495863,31683.989815,31700.238426,34828.672685,22882.032258,22898.205991,26016.440092,579.054031,573.973538,587.595420,25.623366,25.898981,25.482886,8.481481,2259.313928,2692.969786,4952.283714,671.409897,886.074594,1557.484490,55.512706,13.594544,12.088939,5.050822,1.120329,5.568386,4.534753,56.485426,2.437220,4.557549,0.420404
std,533.437627,303.402950,235.195758,2.815905,1.452959,1.586259,83.016522,48.230435,35.730717,32.837487,14.547948,18.941059,39.379074,20.021061,19.983782,2.963964,1.408322,1.726549,357.080342,204.955422,156.458890,6.571219,3.127107,3.731440,34.826886,17.839573,17.517535,36.008551,23.042651,13.211298,21.886462,22.860664,22.241805,36.259747,29.338908,29.549690,40.353853,25.847849,25.115193,23.029231,27.225774,29.246993,28.351313,15.985368,16.863692,19.697588,5.761373e+08,14.657943,13.711589,8.438596,11.784070,5.528239,2.215884,12.088829,4.933873e+08,26.520602,9.771877,19.512942,15.420069,9.516798,1.089347e+08,11.864783,7.284502,0.598765,1.968414,6.738881,6.698347,5.463229e+08,10.350832,9.339267,5.048075,4.634420,5.893753,6.346560,11.105261,4.135208e+08,12.205473,6.429826,3.767013,7.338886,9.799552,11.306864,10.293783,8.678174e+07,14.662146,0.669117,1.563478,16.439554,11.759606,20.364571,15.657336,4.440124,1.819423,5.921256,1.188421,0.737055,0.175734,7.833699,1.524855,14244.658708,14232.923993,12553.897504,12565.515785,12546.049106,11379.400744,11968.374689,11948.684813,10610.028858,70.227537,79.173507,73.971511,3.419602,3.862909,3.449092,0.900728,3132.081171,3434.189047,6498.582577,1795.864881,2858.849285,4548.789999,25.450311,18.943409,18.773424,8.495520,7.064701,7.568071,7.922092,17.515264,2.481065,7.070226,4.161418
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.179270e+05,0.000000,0.000000,0.000000,0.000000,-6.000000,-1.000000,0.000000,-6.432834e+06,0.000000,0.000000,-12.000000,-332.000000,-2.000000,3.301600e+04,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.073170e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-36.000000,5.000000e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.000000,1.000350e+05,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-2.000000,-2.000000,-2.000000,-2.000000,1.000000,1.000000,1.000000,-2.000000,2393.000000,2393.000000,2393.000000,9418.000000,9418.000000,10135.000000,3918.000000,4784.000000,4840.000000,390.000000,380.000000,400.000000,16.000000,15.000000,15.000000,6.000000,0.000000,0.000000,4.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,31.000000,14.000000,15.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,19.000000,9.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,36.000000,32.000000,40.000000,0.000000,39.000000,40.000000,0.000000,22.000000,31.000000,40.000000,29.000000,29.000000,42.000000,13.000000,85.000000,75.000000,5.674203e+07,18.000000,21.000000,0.000000,15.000000,1.000000,1.000000,5.000000,7.009263e+06,46.000000,0.000000,5.000000,0.000000,0.000000,2.420042e+06,95.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.173597e+07,35.000000,0.000000,0.000000,7.000000,7.000000,10.000000,7.000000,6.730487e+06,32.000000,0.000000,0.000000,6.000000,10.000000,18.000000,0.000000,2.475196e+06,19.000000,0.000000,0.000000,4.000000,3.000000,17.000000,0.000000,7.000000,2.000000,18.000000,1.000000,1.000000,2.000000,10.000000,-2.000000,22174.500000,22174.500000,29356.000000,21870.500000,21898.250000,26725.000000,12607.250000,12608.250000,18302.250000,530.000000,520.000000,540.000000,23.000000,24.000000,24.000000,8.000000,433.000000,552.000000,1017.000000,60.000000,95.250000,178.000000,40.000000,3.000000,3.000000,1.000000,0.000000,1.000000,0.000000,50.000000,1.000000,1.000000,0.000000
50%,91.000000,44.000000,46.000000,0.000000,0.000000,0.000000,4.000000,2.000000,2.000000,4.000000,2.000000,2.000000,3.000000,1.000000,1.000000,0.000000,0.000000,0.000000,68.000000,33.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,52.000000,48.000000,57.000000,36.000000,60.000000,63.000000,50.000000,40.000000,49.000000,56.000000,50.000000,50.000000,61.000000,23.000000,96.000000,92.000000,1.271384e+08,29.000000,29.000000,0.000000,20.000000,3.000000,1.000000,9.000000,2.334597e+07,68.000000,1.000000,13.000000,3.000000,2.000000,7.175490e+06,99.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.199706e+08,42.000000,1.000000,2.000000,10.000000,10.000000,13.000000,12.000000,2.364763e+07,40.000000,0.000000,0.000000,9.000000,17.000000,23.000000,0.000000,7.517764e+06,28.000000,0.000000,0.000000,8.000000,11.000000,35.000000,0.000000,11.000000,3.000000,21.000000,2.000000,2.000000,2.000000,13.000000,-2.000000,32465.500000,32465.500000,36604.500000,29096.000000,29096.000000,33696.000000,19713.500000,19713.500000,24719.000000,570.000000,560.000000,580.000000,25.000000,25.000000,25.000000,8.000000,1033.000000,1325.000000,2391.000000,204.000000,321.000000,558.000000,61.000000,7.000000,6.000000,2.000000,0.000000,3.000000,2.000000,58.000000,2.000000,2.000000,0.000000
75%,229.750000,115.000000,117.000000,1.000000,0.000000,0.000000,18.000000,9.000000,8.000000,12.000000,6.000000,7.000000,11.000000,5.000000,5.000000,0.000000,0.000000,0.000000,170.750000,85.000000,84.000000,2.000000,1.000000,1.000000,3.000000,2.000000,2.000000,5.000000,3.000000,2.000000,67.000000,64.000000,71.000000,67.000000,80.000000,81.000000,100.000000,58.000000,65.000000,71.000000,67.000000,72.000000,80.000000,32.000000,100.000000,99.000000,3.180440e+08,39.000000,38.000000,0.000000,27.000000,5.000000,2.000000,15.000000,6.408374e+07,84.000000,5.000000,27.000000,10.000000,6.000000,1.965560e+07,100.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.031459e+08,48.000000,9.000000,5.000000,13.000000,13.000000,17.000000,21.000000,6.203499e+07,46.000000,1.000000,1.000000,13.000000,24.000000,30.000000,3.000000,1.825691e+07,38.000000,0.000000,0.000000,16.000000,20.000000,47.000000,13.000000,14.000000,5.000000,24.000000,3.000000,2.000000,2.000000,17.000000,-2.000000,44973.000000,44973.000000,45973.000000,39756.750000,39756.750000,41777.750000,31724.000000,31724.000000,32918.250000,620.000000,610.000000,630.000000,27.000000,28.000000,27.000000,9.000000,2766.000000,3492.000000,6139.000000,696.250000,907.000000,1585.500000,75.000000,15.000000,12.000000,6.000000,1.000000,7.000000,6.000000,65.000000,3.000000,5.000000,0.000000
max,6787.000000,3983.000000,2804.000000,39.000000,25.000000,27.000000,1001.000000,606.000000,499.000000,604.000000,307.000000,312.000000,683.000000,364.000000,372.000000,79.000000,32.000000,52.000000,4094.000000,2367.000000,1754.000000,103.000000,44.000000,72.000000,807.000000,324.000000,483.000000,1027.000000,671.000000,356.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,5.290396e+09,100.000000,76.000000,69.000000,98.000000,64.000000,22.000000,98.000000,8.257036e+09,367.000000,94.000000,131.000000,100.000000,100.000000,1.463057e+09,100.000000,58.000000,10.000000,25.000000,85.000000,50.000000,5.533926e+09,76.000000,65.000000,40.000000,37.000000,87.000000,60.000000,69.000000,6.894039e+09,100.000000,71.000000,53.000000,57.000000,53.000000,99.000000,100.000000,1.041293e+09,100.000000,7.000000,15.000000,79.000000,62.000000,93.000000,81.000000,18.000000,7.000000,33.000000,5.000000,9.000000,2.000000,122.000000,5.000000,67665.000000,67665.000000,67665.000000,74888.000000,74888.000000,74888.000000,61042.000000,61042.000000,61042.000000,800.000000,800.000000,800.000000,35.000000,36.000000,36.000000,12.000000,23198.000000,24194.000000,45628.000000,41682.000000,87312.000000,128994.000000,100.000000,100.000000,100.000000,99.000000,100.000000,87.000000,99.000000,100.000000,30.000000,95.000000,99.000000

## Graduation Rates

In [7]:
df.filter(regex="Grad").describe().loc["mean"].sort_values()

Graduation rate  Black  non-Hispanic (DRVGR2019)                             41.239763
Graduation rate  American Indian or Alaska Native (DRVGR2019)                41.953737
Graduation rate  Hispanic (DRVGR2019)                                        47.868434
Graduation rate  men (DRVGR2019)                                             47.922598
Graduation rate  two or more races (DRVGR2019)                               48.453488
Graduation rate  Native Hawaiian or Other Pacific Islander (DRVGR2019)       48.973489
Graduation rate  Race/ethnicity unknown (DRVGR2019)                          50.320922
Graduation rate  total cohort (DRVGR2019)                                    51.535205
Graduation rate  White  non-Hispanic (DRVGR2019)                             54.559891
Graduation rate  women (DRVGR2019)                                           54.874547
Graduation rate  Asian/Native Hawaiian/Other Pacific Islander (DRVGR2019)    57.539639
Graduation rate  Nonresident alien (DRVGR2019)                               58.502545
Graduation rate  Asian (DRVGR2019)                                           59.046708
Name: mean, dtype: float64

## Schema

In [8]:
# read in our schema
schema = pd.read_csv("data/4_year/schema.csv")

In [9]:
# Make a Pandas groupby that groups by variable name
groups = schema.groupby(by="VariableName")

In [10]:
#view all of our categorical groups
groups.head(2)

,VariableName,Value,ValueLabel
0,State abbreviation (HD2018),AL,Alabama
1,State abbreviation (HD2018),AK,Alaska
58,Sector of institution (HD2018),1,"Public, 4-year or above"
59,Sector of institution (HD2018),2,"Private not-for-profit, 4-year or above"
66,Historically Black College or University (HD2018),1,Yes
67,Historically Black College or University (HD2018),2,No
68,Carnegie Classification 2018: Enrollment Profi...,1,Exclusively undergraduate two-year
69,Carnegie Classification 2018: Enrollment Profi...,2,Exclusively undergraduate four-year
76,Carnegie Classification 2018: Size and Setting...,1,"Two-year, very small"
77,Carnegie Classification 2018: Size and Setting...,2,"Two-year, small"
95,Carnegie Classification 2018: Basic (HD2018),1,Associate's Colleges: High Transfer-High Tradi...
96,Carnegie Classification 2018: Basic (HD2018),2,Associate's Colleges: High Transfer-Mixed Trad...
128,Institution size category (HD2018),1,"Under 1,000"
129,Institution size category (HD2018),2,"1,000 - 4,999"
135,Parent/child indicator - Finance (FLAGS2019),1,Parent record - includes data from branch camp...
136,Parent/child indicator - Finance (FLAGS2019),2,Child record - data reported with parent campus

**African American And Native American mean graduation rates are  38 and 37 respectively**

# Overview of Missing Data

## Admissions Test Scores

In [11]:
# How many schools failed to report their SAT Scores
df.filter(regex="SAT|ACT").isna().sum()

SAT Critical Reading 75th percentile score (ADM2014_RV)    1680
SAT Writing 75th percentile score (ADM2014_RV)             2128
SAT Math 75th percentile score (ADM2014_RV)                1667
ACT Composite 75th percentile score (ADM2014_RV)           1622
ACT English 75th percentile score (ADM2014_RV)             1767
ACT Math 75th percentile score (ADM2014_RV)                1765
ACT Writing 75th percentile score (ADM2014_RV)             2549
dtype: int64

## Finances

In [12]:
# How many schools failed to report their Finances
df.filter(regex="revenues|expenses").isna().sum().sample(5)

Public service expenses as a percent of total core expenses (GASB) (DRVF2019)      2080
Research expenses as a percent of total core expenses (GASB) (DRVF2019)            2080
Instruction expenses as a percent of total core expenses (GASB) (DRVF2019)         2080
Academic support expenses as a percent of total core expenses (GASB) (DRVF2019)    2080
Instruction expenses as a percent of total core expenses (FASB) (DRVF2019)         1156
dtype: int64

Notice that GASB, FASB and for-profit institutions are different groups

## Percentage of Enrollment by Race

In [13]:
df.filter(regex="Percent of total").isna().sum()

Percent of total enrollment that are White (DRVEF2014_RV)                                        170
Percent of total enrollment that are Black or African American  (DRVEF2014_RV)                   170
Percent of total enrollment that are Hispanic/Latino (DRVEF2014_RV)                              170
Percent of total enrollment that are Asian/Native Hawaiian/Pacific Islander (DRVEF2014_RV)       170
Percent of total enrollment that are American Indian or Alaska Native (DRVEF2014_RV)             170
Percent of total enrollment that are Race/ethnicity unknown (DRVEF2014_RV)                       170
Percent of total enrollment that are Nonresident Alien (DRVEF2014_RV)                            170
Percent of total enrollment that are women (DRVEF2014_RV)                                        170
Percent of total enrollment that are two or more races (DRVEF2014_RV)                            170
Percent of total enrollment that are Asian (DRVEF2014_RV)                                        170
Percent of total enrollment that are Native Hawaiian or Other Pacific Islander (DRVEF2014_RV)    170
dtype: int64

## Staff Diversity

In [14]:
# Staff Diveristy NA counts
df.filter(regex="instructional").isna().sum().head()

Grand total (S2019_IS  All instructional staff)                               380
Grand total men (S2019_IS  All instructional staff)                           380
Grand total women (S2019_IS  All instructional staff)                         380
American Indian or Alaska Native total (S2019_IS  All instructional staff)    380
American Indian or Alaska Native men (S2019_IS  All instructional staff)      380
dtype: int64

## Categorical

In [15]:
df.filter(regex="State abb|Carnegie|Historically|Sector|size category|(FLAGS2019)").isna().sum()

Carnegie Classification 2018: Size and Setting (HD2018)      55
Carnegie Classification 2018: Enrollment Profile (HD2018)    55
Carnegie Classification 2018: Basic (HD2018)                 55
State abbreviation (HD2018)                                  55
Institution size category (HD2018)                           55
Sector of institution (HD2018)                               55
Historically Black College or University (HD2018)            55
Parent/child indicator - Finance (FLAGS2019)                 21
dtype: int64

# Cleanning for Categorical Variables

## Non-Location Categories

In [16]:
# Selecting categorical columns
categorical_df = df.filter(regex="Carnegie|Historically|Sector|size category|(FLAGS2019)").copy(deep=True)

In [17]:
categorical_df.head()

,Carnegie Classification 2018: Size and Setting (HD2018),Carnegie Classification 2018: Enrollment Profile (HD2018),Carnegie Classification 2018: Basic (HD2018),Institution size category (HD2018),Sector of institution (HD2018),Historically Black College or University (HD2018),Parent/child indicator - Finance (FLAGS2019)
UnitID,,,,,,,
177834,18.0,7.0,25.0,2.0,2.0,2.0,-2.0
180203,1.0,1.0,33.0,1.0,4.0,2.0,-2.0
222178,14.0,4.0,18.0,3.0,2.0,2.0,-2.0
138558,10.0,2.0,23.0,2.0,1.0,2.0,-2.0
488031,6.0,6.0,31.0,1.0,3.0,2.0,-2.0

In [18]:
# Using Groupby object from schema to fill categorical variables with their string values
for i in categorical_df.columns:
    val_label = groups.get_group(i)[["Value", "ValueLabel"]].transpose()

    val_label.columns = val_label.loc["Value"]

    val_label.drop("Value", inplace=True)

    map_ = val_label.loc["ValueLabel"].to_dict()

    map_ ={int(i): v for i,v in map_.items()}
    map_[-100] = "isMissing"
    
    categorical_df[i] = categorical_df[i].fillna(-100).astype(int).replace(map_)

In [19]:
# View the changes
categorical_df.head()

,Carnegie Classification 2018: Size and Setting (HD2018),Carnegie Classification 2018: Enrollment Profile (HD2018),Carnegie Classification 2018: Basic (HD2018),Institution size category (HD2018),Sector of institution (HD2018),Historically Black College or University (HD2018),Parent/child indicator - Finance (FLAGS2019)
UnitID,,,,,,,
177834,Exclusively graduate/professional,Exclusively graduate,Special Focus Four-Year: Medical Schools & Cen...,"1,000 - 4,999","Private not-for-profit, 4-year or above",No,Not applicable
180203,"Two-year, very small",Exclusively undergraduate two-year,Tribal Colleges,"Under 1,000","Public, 2-year",No,Not applicable
222178,"Four-year, medium, highly residential",High undergraduate,Master's Colleges & Universities: Larger Programs,"5,000 - 9,999","Private not-for-profit, 4-year or above",No,Not applicable
138558,"Four-year, small, primarily residential",Exclusively undergraduate four-year,Baccalaureate/Associate's Colleges: Mixed Bacc...,"1,000 - 4,999","Public, 4-year or above",No,Not applicable
488031,"Four-year, very small, primarily nonresidential",Majority graduate,Special Focus Four-Year: Law Schools,"Under 1,000","Private for-profit, 4-year or above",No,Not applicable

In [20]:
# Clean the column names by getting rid of the (HD2018)
categorical_df.rename(columns=lambda x: re.sub(r'\(.*\)', '', x), inplace=True)
categorical_df.rename(columns=lambda x: x.replace(r'  ', ' '), inplace=True)
categorical_df.rename(columns=lambda x: x.strip(), inplace=True)

In [21]:
categorical_df.head()

,Carnegie Classification 2018: Size and Setting,Carnegie Classification 2018: Enrollment Profile,Carnegie Classification 2018: Basic,Institution size category,Sector of institution,Historically Black College or University,Parent/child indicator - Finance
UnitID,,,,,,,
177834,Exclusively graduate/professional,Exclusively graduate,Special Focus Four-Year: Medical Schools & Cen...,"1,000 - 4,999","Private not-for-profit, 4-year or above",No,Not applicable
180203,"Two-year, very small",Exclusively undergraduate two-year,Tribal Colleges,"Under 1,000","Public, 2-year",No,Not applicable
222178,"Four-year, medium, highly residential",High undergraduate,Master's Colleges & Universities: Larger Programs,"5,000 - 9,999","Private not-for-profit, 4-year or above",No,Not applicable
138558,"Four-year, small, primarily residential",Exclusively undergraduate four-year,Baccalaureate/Associate's Colleges: Mixed Bacc...,"1,000 - 4,999","Public, 4-year or above",No,Not applicable
488031,"Four-year, very small, primarily nonresidential",Majority graduate,Special Focus Four-Year: Law Schools,"Under 1,000","Private for-profit, 4-year or above",No,Not applicable

## Location Data

In [22]:
# Selecting location data
location_data = df.filter(regex="State abbr|City").copy(deep=True)
location_data.fillna("isMissing", inplace=True)

# Financial Data

Universities report their finances to the Ipeds data center as either a GASB, FASB, or for-profit institution. Therefore FASB and for-profit institutions will have all null values in the GASB finance columns. I will clean this by preserving the type of school they are (FASB, GASB, or for-profit) whilst merging finance columns into one shared column for FASB, GASB and for-profit colleges.

In [23]:
gasb_df = df.filter(regex="(GASB)").copy(deep=True)

In [24]:
gasb_df.head()

,Core revenues total dollars (GASB) (DRVF2019),Tuition and fees as a percent of core revenues (GASB) (DRVF2019),State appropriations as percent of core revenues (GASB) (DRVF2019),Local appropriations as a percent of core revenues (GASB) (DRVF2019),Government grants and contracts as a percent of core revenues (GASB) (DRVF2019),Private gifts grants and contracts as a percent of core revenues (GASB) (DRVF2019),Investment return as a percent of core revenues (GASB) (DRVF2019),Other revenues as a percent of core revenues (GASB) (DRVF2019),Core expenses total dollars (GASB) (DRVF2019),Instruction expenses as a percent of total core expenses (GASB) (DRVF2019),Research expenses as a percent of total core expenses (GASB) (DRVF2019),Public service expenses as a percent of total core expenses (GASB) (DRVF2019),Academic support expenses as a percent of total core expenses (GASB) (DRVF2019),Student service expenses as a percent of total core expenses (GASB) (DRVF2019),Institutional support expenses as a percent of total core expenses (GASB) (DRVF2019),Other core expenses as a percent of total core expenses (GASB) (DRVF2019)
UnitID,,,,,,,,,,,,,,,,
177834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180203,7078959.0,2.0,1.0,0.0,60.0,7.0,1.0,29.0,7294344.0,29.0,3.0,7.0,3.0,8.0,16.0,36.0
222178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138558,70491879.0,17.0,37.0,0.0,17.0,2.0,0.0,28.0,50201124.0,42.0,0.0,3.0,15.0,9.0,19.0,13.0
488031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
fasb_df = df.filter(regex="(FASB)").copy(deep=True)

In [26]:
fasb_df.head()

,Core revenues total dollars (FASB) (DRVF2019),Tuition and fees as a percent of core revenues (FASB) (DRVF2019),Government grants and contracts as a percent of core revenues (FASB) (DRVF2019),Private gifts grants contracts/contributions from affiliated entities as a percent of core revenues (FASB) (DRVF2019),Investment return as a percent of core revenues (FASB) (DRVF2019),Other revenues as a percent of core revenues (FASB) (DRVF2019),Core expenses total dollars (FASB) (DRVF2019),Instruction expenses as a percent of total core expenses (FASB) (DRVF2019),Research expenses as a percent of total core expenses (FASB) (DRVF2019),Public service expenses as a percent of total core expenses (FASB) (DRVF2019),Academic support expenses as a percent of total core expenses (FASB) (DRVF2019),Student service expenses as a percent of total core expenses (FASB) (DRVF2019),Institutional support expenses as a percent of total core expenses (FASB) (DRVF2019),Other core expenses as a percent of total core expenses (FASB) (DRVF2019)
UnitID,,,,,,,,,,,,,,
177834,174782780.0,80.0,2.0,6.0,6.0,6.0,148677539.0,50.0,3.0,0.0,27.0,4.0,15.0,1.0
180203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222178,136379482.0,57.0,4.0,17.0,18.0,4.0,121513039.0,38.0,1.0,2.0,10.0,26.0,24.0,0.0
138558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
for_profit = df.filter(regex="(for-profit institut)").copy(deep=True)

In [28]:
for_profit.head()

,Core revenues total dollars (for-profit institutions) (DRVF2019),Tuition and fees as a percent of core revenues (for-profit institutions) (DRVF2019),Government grants and contracts as a percent of core revenues (for-profit institutions) (DRVF2019),Private gifts grants contracts as a percent of core revenues (for-profit institutions) (DRVF2019),Investment return as a percent of core revenues (for-profit institutions) (DRVF2019),Sales and services of educational activities as a percent of core revenues (for-profit institutions) (DRVF2019),Other revenues as a percent of core revenues (for-profit institutions) (DRVF2019),Core expenses total dollars (for-profit institutons) (DRVF2019),Instruction expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Research expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Public service expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Academic support expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Student service expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Institutional support expenses as a percent of total core expenses (for-profit institutions) (DRVF2019),Other core expenses as a percent of total core expenses (for-profit institutions) (DRVF2019)
UnitID,,,,,,,,,,,,,,,
177834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488031,1555377.0,99.0,0.0,0.0,1.0,0.0,0.0,1604693.0,6.0,0.0,0.0,16.0,16.0,18.0,45.0

In [29]:
# create GASB, FASB and forProfit columns
gasb_df["is_GASB"] = gasb_df.sum(axis=1).astype(int).apply(lambda x: 1 if x != 0 else 0)
gasb_df["is_FASB"] = 0
gasb_df["is_forProfit"] = 0

fasb_df["is_GASB"] = 0
fasb_df["is_FASB"] = fasb_df.sum(axis=1).astype(int).apply(lambda x: 1 if x != 0 else 0)
fasb_df["is_forProfit"] = 0

for_profit["is_GASB"] = 0
for_profit["is_FASB"] = 0
for_profit["is_forProfit"] = for_profit.sum(axis=1).astype(int).apply(lambda x: 1 if x != 0 else 0)

In [30]:
# View how many of each typ of schoo their are
len(for_profit[for_profit.is_forProfit == 1])

358

In [31]:
gasb_df.columns[2:4]

Index(['State appropriations as percent of core revenues  (GASB) (DRVF2019)', 'Local appropriations as a percent of core revenues (GASB) (DRVF2019)'], dtype='object')

In [32]:
# Separating out State and Local Appropriations which are unique to gasb
state_local = gasb_df[gasb_df.columns[2:4]]
gasb_df = gasb_df.drop(gasb_df.columns[2:4], axis=1).copy(deep=True)

In [33]:
state_local.rename(columns=lambda x: re.sub(r'\(.*\)', '', x), inplace=True)
state_local.rename(columns=lambda x: x.replace(r'  ', ' '), inplace=True)
state_local.rename(columns=lambda x: x.strip(), inplace=True)

## Merging GASB, FASB and for-profit institutions Finances into one column

In order to merge GASB, FASB, and for-profit institutions we need for all of their column names to be the same value

In [34]:

fasb_df.rename(columns=lambda x: re.sub(r'\(.*\)', '', x), inplace=True)
fasb_df.rename(columns=lambda x: x.replace(r'  ', ' '), inplace=True)
fasb_df.rename(columns=lambda x: x.strip(), inplace=True)

fasb_df = fasb_df[sorted(fasb_df.columns)]

In [35]:
gasb_df.rename(columns=lambda x: re.sub(r'\(.*\)', '', x), inplace=True)
gasb_df.rename(columns=lambda x: x.replace(r'  ', ' '), inplace=True)
gasb_df.rename(columns=lambda x: x.strip(), inplace=True)

gasb_df = gasb_df[sorted(gasb_df.columns)]

In [36]:
for_profit.rename(columns=lambda x: re.sub(r'\(.*\)', '', x), inplace=True)
for_profit.rename(columns=lambda x: x.replace(r'  ', ' '), inplace=True)
for_profit.rename(columns=lambda x: x.strip(), inplace=True)

# Typo in column name government grants and contracts
for_profit.rename(columns=lambda x: re.sub(r'grants contracts', 'grants and contracts', x), inplace=True)
for_profit = for_profit[sorted(for_profit.columns)]

Lets view the data frames

In [37]:
for_profit.head(2)

,Academic support expenses as a percent of total core expenses,Core expenses total dollars,Core revenues total dollars,Government grants and contracts as a percent of core revenues,Institutional support expenses as a percent of total core expenses,Instruction expenses as a percent of total core expenses,Investment return as a percent of core revenues,Other core expenses as a percent of total core expenses,Other revenues as a percent of core revenues,Private gifts grants and contracts as a percent of core revenues,Public service expenses as a percent of total core expenses,Research expenses as a percent of total core expenses,Sales and services of educational activities as a percent of core revenues,Student service expenses as a percent of total core expenses,Tuition and fees as a percent of core revenues,is_FASB,is_GASB,is_forProfit
UnitID,,,,,,,,,,,,,,,,,,
177834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
180203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0

In [38]:
gasb_df.head(2)

,Academic support expenses as a percent of total core expenses,Core expenses total dollars,Core revenues total dollars,Government grants and contracts as a percent of core revenues,Institutional support expenses as a percent of total core expenses,Instruction expenses as a percent of total core expenses,Investment return as a percent of core revenues,Other core expenses as a percent of total core expenses,Other revenues as a percent of core revenues,Private gifts grants and contracts as a percent of core revenues,Public service expenses as a percent of total core expenses,Research expenses as a percent of total core expenses,Student service expenses as a percent of total core expenses,Tuition and fees as a percent of core revenues,is_FASB,is_GASB,is_forProfit
UnitID,,,,,,,,,,,,,,,,,
177834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
180203,3.0,7294344.0,7078959.0,60.0,16.0,29.0,1.0,36.0,29.0,7.0,7.0,3.0,8.0,2.0,0,1,0

In [39]:
fasb_df.head(2)

,Academic support expenses as a percent of total core expenses,Core expenses total dollars,Core revenues total dollars,Government grants and contracts as a percent of core revenues,Institutional support expenses as a percent of total core expenses,Instruction expenses as a percent of total core expenses,Investment return as a percent of core revenues,Other core expenses as a percent of total core expenses,Other revenues as a percent of core revenues,Private gifts grants contracts/contributions from affiliated entities as a percent of core revenues,Public service expenses as a percent of total core expenses,Research expenses as a percent of total core expenses,Student service expenses as a percent of total core expenses,Tuition and fees as a percent of core revenues,is_FASB,is_GASB,is_forProfit
UnitID,,,,,,,,,,,,,,,,,
177834,27.0,148677539.0,174782780.0,2.0,15.0,50.0,6.0,1.0,6.0,6.0,0.0,3.0,4.0,80.0,1,0,0
180203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0

**Lets make sure each subset contains the same amount of Columns**

In [40]:
set(for_profit.columns) - set(gasb_df.columns)

{'Sales and services of educational activities as a percent of core revenues'}

In [41]:
# Viewing sales and services
print(for_profit.columns[-5])
print(for_profit.columns[-6])
print(for_profit[for_profit.columns[-6]].isna().sum())
print(for_profit[for_profit.columns[-5]].isna().sum())

Student service expenses as a percent of total core expenses
Sales and services of educational activities as a percent of core revenues
2488
2488

In [42]:
(for_profit[for_profit.columns[-5]] + for_profit[for_profit.columns[-6]]).isna().sum()

2488

In [43]:
# Student services = student services + sales and services
for_profit[for_profit.columns[-5]] = for_profit[for_profit.columns[-5]] + for_profit[for_profit.columns[-6]]

In [44]:
# drop sales and services
for_profit.drop(for_profit.columns[-6], axis=1, inplace=True)

In [45]:
drop_sales = 'Sales and services of educational activities as a percent of core revenues'

Renaming private grants and contracts so that is is the same for fasb, gasb and nasb

In [46]:
gasb_df.columns[9] # this column is different for gasb but they contain the same data

'Private gifts grants and contracts as a percent of core revenues'

In [47]:
fasb_df.columns[9] # I need to rename this column so that it is the same as GASB and for-profit institutions

'Private gifts grants contracts/contributions from affiliated entities as a percent of core revenues'

In [48]:
fasb_df.rename({fasb_df.columns[9]: gasb_df.columns[9]}, axis=1, inplace=True)

**Sales and services are only recorded for for-profit institutions so I will combine that column with other services so that Services include Sales and Services**

In [49]:
#check to see if all columns are equal
print("gasb == fasb: ", gasb_df.columns == fasb_df.columns)
print("fasb == for_profit: ", fasb_df.columns == for_profit.columns)

gasb == fasb:  [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]
fasb == for_profit:  [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]

In [50]:
#check 

fasb_df.iloc[:, -3:]

        is_FASB  is_GASB  is_forProfit
UnitID
177834        1        0             0
180203        0        0             0
222178        1        0             0
138558        0        0             0
488031        0        0             0
...         ...      ...           ...
217059        1        0             0
141361        1        0             0
206695        0        0             0
204255        0        0             0
458575        0        0             0

[2846 rows x 3 columns]

### Finally Merging all together

In [51]:
finances_df = pd.concat([gasb_df, fasb_df, for_profit])

In [52]:
#check
finances_df.iloc[:, -3:]

        is_FASB  is_GASB  is_forProfit
UnitID
177834        0        0             0
180203        0        1             0
222178        0        0             0
138558        0        1             0
488031        0        0             0
...         ...      ...           ...
217059        0        0             0
141361        0        0             0
206695        0        0             0
204255        0        0             0
458575        0        0             0

[8538 rows x 3 columns]

In [53]:
finances_df["isnan"] = finances_df.isna().sum(axis=1)

In [54]:
#check
finances_df.iloc[:, -4:]

        is_FASB  is_GASB  is_forProfit  isnan
UnitID
177834        0        0             0     14
180203        0        1             0      0
222178        0        0             0     14
138558        0        1             0      0
488031        0        0             0     14
...         ...      ...           ...    ...
217059        0        0             0     14
141361        0        0             0     14
206695        0        0             0     14
204255        0        0             0     14
458575        0        0             0     14

[8538 rows x 4 columns]

In [55]:
finances_df = finances_df[finances_df["isnan"] != 14].copy(deep=True)

In [56]:
#check
finances_df

,Academic support expenses as a percent of total core expenses,Core expenses total dollars,Core revenues total dollars,Government grants and contracts as a percent of core revenues,Institutional support expenses as a percent of total core expenses,Instruction expenses as a percent of total core expenses,Investment return as a percent of core revenues,Other core expenses as a percent of total core expenses,Other revenues as a percent of core revenues,Private gifts grants and contracts as a percent of core revenues,Public service expenses as a percent of total core expenses,Research expenses as a percent of total core expenses,Student service expenses as a percent of total core expenses,Tuition and fees as a percent of core revenues,is_FASB,is_GASB,is_forProfit,isnan
UnitID,,,,,,,,,,,,,,,,,,
180203,3.0,7294344.0,7078959.0,60.0,16.0,29.0,1.0,36.0,29.0,7.0,7.0,3.0,8.0,2.0,0,1,0,0
138558,15.0,50201124.0,70491879.0,17.0,19.0,42.0,0.0,13.0,28.0,2.0,3.0,0.0,9.0,17.0,0,1,0,0
126182,7.0,35725137.0,52099218.0,51.0,15.0,53.0,1.0,5.0,9.0,5.0,3.0,0.0,18.0,34.0,0,1,0,0
100654,6.0,146878227.0,143112797.0,30.0,11.0,22.0,0.0,29.0,6.0,2.0,9.0,9.0,14.0,33.0,0,1,0,0
100724,9.0,134888910.0,134993142.0,25.0,27.0,29.0,1.0,16.0,7.0,2.0,4.0,3.0,12.0,30.0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458229,5.0,40658057.0,64468935.0,0.0,43.0,49.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,100.0,0,0,1,0
458210,5.0,61800247.0,97992780.0,0.0,43.0,49.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,100.0,0,0,1,0
490133,8.0,7497616.0,8972118.0,0.0,63.0,17.0,0.0,0.0,0.0,0.0,0.0,2.0,16.0,94.0,0,0,1,0
224660,23.0,9920436.0,9912034.0,27.0,10.0,28.0,0.0,16.0,14.0,0.0,15.0,0.0,8.0,59.0,0,0,1,0
224679,25.0,14831336.0,14868051.0,35.0,13.0,22.0,0.0,16.0,6.0,0.0,15.0,0.0,9.0,59.0,0,0,1,0

In [57]:
finances_df.drop("isnan", axis=1, inplace=True)

In [58]:
#changelog
finances_df = finances_df.reset_index().drop_duplicates(subset="UnitID")

In [59]:
finances_df.set_index("UnitID", inplace=True)

In [60]:
print(len(finances_df))
print(finances_df.isna().sum())

2814
Academic support expenses as a percent of total core expenses         0
Core expenses total dollars                                           0
Core revenues total dollars                                           0
Government grants and contracts as a percent of core revenues         1
Institutional support expenses as a percent of total core expenses    0
Instruction expenses as a percent of total core expenses              0
Investment return as a percent of core revenues                       1
Other core expenses as a percent of total core expenses               0
Other revenues as a percent of core revenues                          1
Private gifts grants and contracts as a percent of core revenues      1
Public service expenses as a percent of total core expenses           0
Research expenses as a percent of total core expenses                 0
Student service expenses as a percent of total core expenses          0
Tuition and fees as a percent of core revenues                        1
is_FASB                                                               0
is_GASB                                                               0
is_forProfit                                                          0
dtype: int64

# Find any possible accidental Values

## Negative Values

In [61]:
neg_cols = finances_df.columns[finances_df[finances_df < 0].isna().sum() != 6197]

In [62]:
neg_cols

Index(['Academic support expenses as a percent of total core expenses',
       'Core expenses total dollars', 'Core revenues total dollars',
       'Government grants and contracts as a percent of core revenues',
       'Institutional support expenses as a percent of total core expenses',
       'Instruction expenses as a percent of total core expenses',
       'Investment return as a percent of core revenues',
       'Other core expenses as a percent of total core expenses',
       'Other revenues as a percent of core revenues',
       'Private gifts grants and contracts as a percent of core revenues',
       'Public service expenses as a percent of total core expenses',
       'Research expenses as a percent of total core expenses',
       'Student service expenses as a percent of total core expenses',
       'Tuition and fees as a percent of core revenues', 'is_FASB', 'is_GASB',
       'is_forProfit'],
      dtype='object')

In [63]:
neg_reporters = set()
for i in neg_cols:
    for j in finances_df[finances_df[i]< 0][i].index:
        neg_reporters.add(j)

In [64]:
len(neg_reporters)

109

## Lets have a look at these negative percentages

**These schools must have had some negative return on investment, so this information remains accurate and won't be tampered with** Lets Insure that their revenues add up to roughly %100 and their expenses do the same

In [65]:
finances_df["revenues_percentage_sum"] = finances_df.filter(regex="as a percent.*revenues").sum(axis=1)

In [66]:
finances_df["expenses_percentage_sum"] = finances_df.filter(regex="as a percent.*expenses").sum(axis=1)

In [67]:
finances_df[finances_df["revenues_percentage_sum"] < 75]

,Academic support expenses as a percent of total core expenses,Core expenses total dollars,Core revenues total dollars,Government grants and contracts as a percent of core revenues,Institutional support expenses as a percent of total core expenses,Instruction expenses as a percent of total core expenses,Investment return as a percent of core revenues,Other core expenses as a percent of total core expenses,Other revenues as a percent of core revenues,Private gifts grants and contracts as a percent of core revenues,Public service expenses as a percent of total core expenses,Research expenses as a percent of total core expenses,Student service expenses as a percent of total core expenses,Tuition and fees as a percent of core revenues,is_FASB,is_GASB,is_forProfit,revenues_percentage_sum,expenses_percentage_sum
UnitID,,,,,,,,,,,,,,,,,,,
138558,15.0,50201124.0,70491879.0,17.0,19.0,42.0,0.0,13.0,28.0,2.0,3.0,0.0,9.0,17.0,0,1,0,64.0,101.0
100654,6.0,146878227.0,143112797.0,30.0,11.0,22.0,0.0,29.0,6.0,2.0,9.0,9.0,14.0,33.0,0,1,0,71.0,100.0
100724,9.0,134888910.0,134993142.0,25.0,27.0,29.0,1.0,16.0,7.0,2.0,4.0,3.0,12.0,30.0,0,1,0,65.0,100.0
138716,10.0,89924505.0,81754461.0,36.0,15.0,35.0,0.0,28.0,4.0,2.0,4.0,1.0,7.0,21.0,0,1,0,63.0,100.0
175342,9.0,76086915.0,75226337.0,43.0,20.0,23.0,1.0,21.0,12.0,0.0,8.0,9.0,11.0,12.0,0,1,0,68.0,101.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446002,6.0,1970923.0,2113565.0,0.0,5.0,51.0,0.0,34.0,0.0,0.0,0.0,1.0,45.0,58.0,0,0,1,58.0,142.0
429094,27.0,3490318.0,3460747.0,1.0,22.0,38.0,0.0,0.0,1.0,0.0,0.0,1.0,41.0,69.0,0,0,1,71.0,129.0
475635,8.0,478928.0,485447.0,0.0,68.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,73.0,0,0,1,73.0,127.0
480912,31.0,284370.0,285527.0,0.0,19.0,46.0,0.0,0.0,0.0,0.0,0.0,0.0,89.0,15.0,0,0,1,15.0,185.0
493673,7.0,457305.0,455785.0,0.0,43.0,23.0,0.0,16.0,0.0,0.0,0.0,0.0,51.0,61.0,0,0,1,61.0,140.0

### I am chosing to ignore the fact that some schools report revenue percentages that don't add up to 100%. I am guessing that there is a good reason for this i.e negative return on investment and that the information is still accurate and will help our model

In [68]:
finances_df.drop(finances_df.columns[-2:], axis=1, inplace=True)

## Final Merge

### State and Local Appropriations

In [69]:
 finances_df = state_local\
    .reset_index().merge(finances_df.reset_index(), on="UnitID", how="outer").set_index("UnitID")

In [70]:
finances_df.isna().sum()

State appropriations as percent of core revenues                      2080
Local appropriations as a percent of core revenues                    2080
Academic support expenses as a percent of total core expenses           32
Core expenses total dollars                                             32
Core revenues total dollars                                             32
Government grants and contracts as a percent of core revenues           33
Institutional support expenses as a percent of total core expenses      32
Instruction expenses as a percent of total core expenses                32
Investment return as a percent of core revenues                         33
Other core expenses as a percent of total core expenses                 32
Other revenues as a percent of core revenues                            33
Private gifts grants and contracts as a percent of core revenues        33
Public service expenses as a percent of total core expenses             32
Research expenses as a percent of total core expenses                   32
Student service expenses as a percent of total core expenses            32
Tuition and fees as a percent of core revenues                          33
is_FASB                                                                 32
is_GASB                                                                 32
is_forProfit                                                            32
dtype: int64

### Returning Finances Back to the original df

# Final Merge

In [71]:
# Lets clean the column names the same way for all columns with regex
df.rename(columns=lambda x: re.sub(r'\(.*25.*over.*\)', 'Age 25 and over', x), inplace=True)
df.rename(columns=lambda x: re.sub(r'\(.*under.*\)', 'Age 25 and under', x), inplace=True)

df.rename(columns=lambda x: re.sub(r'\(.*instructional staff.*\)', 'instructional staff', x), inplace=True)
df.rename(columns=lambda x: re.sub(r'\(.*\)', '', x), inplace=True)
df.rename(columns=lambda x: x.replace(r'  ', ' '), inplace=True)
df.rename(columns=lambda x: x.strip(), inplace=True)

In [72]:
df = df.loc[:, ~df.columns.duplicated()]

In [73]:
financial_cols = df.filter(regex='revenues|expenses').columns

In [74]:
df.drop(financial_cols, axis=1, inplace=True)

In [75]:
# sort in alphabetical order by university name
df.sort_index(inplace=True)
finances_df.sort_index(inplace=True)

In [76]:
# Both data frames have the same exact indices
(finances_df.index == df.index).sum()

2846

In [77]:
# Its safe to concatenate side by side because we have verified that they have the same exact indices 
final_df = pd.concat([df, finances_df], axis=1)

In [78]:
# lets drop where total graduation rates are missing

In [79]:
grad_rates = final_df.filter(regex="Graduation").columns[0]

In [80]:
final_df.dropna(subset=[grad_rates], inplace=True)

In [81]:
final_df

,Institution Name,City location of institution,Grand total instructional staff,Grand total men instructional staff,Grand total women instructional staff,American Indian or Alaska Native total instructional staff,American Indian or Alaska Native men instructional staff,American Indian or Alaska Native women instructional staff,Asian total instructional staff,Asian men instructional staff,Asian women instructional staff,Black or African American total instructional staff,Black or African American men instructional staff,Black or African American women instructional staff,Hispanic or Latino total instructional staff,Hispanic or Latino men instructional staff,Hispanic or Latino women instructional staff,Native Hawaiian or Other Pacific Islander total instructional staff,Native Hawaiian or Other Pacific Islander men instructional staff,Native Hawaiian or Other Pacific Islander women instructional staff,White total instructional staff,White men instructional staff,White women instructional staff,Two or more races total instructional staff,Two or more races men instructional staff,Two or more races women instructional staff,Race/ethnicity unknown total instructional staff,Race/ethnicity unknown men instructional staff,Race/ethnicity unknown women instructional staff,Nonresident alien total instructional staff,Nonresident alien men instructional staff,Nonresident alien women instructional staff,Graduation rate total cohort,Graduation rate men,Graduation rate women,Graduation rate American Indian or Alaska Native,Graduation rate Asian/Native Hawaiian/Other Pacific Islander,Graduation rate Asian,Graduation rate Native Hawaiian or Other Pacific Islander,Graduation rate Black non-Hispanic,Graduation rate Hispanic,Graduation rate White non-Hispanic,Graduation rate two or more races,Graduation rate Race/ethnicity unknown,Graduation rate Nonresident alien,Transfer-out rate total cohort,Percent of full-time first-time undergraduates awarded any financial aid,Percent of full-time first-time undergraduates awarded federal state local or institutional grant aid,Carnegie Classification 2018: Size and Setting,Carnegie Classification 2018: Enrollment Profile,Carnegie Classification 2018: Basic,State abbreviation,Institution size category,Sector of institution,Historically Black College or University,Student-to-faculty ratio,Parent/child indicator - Finance,Total price for in-district students living on campus 2014-15,Total price for in-state students living on campus 2014-15,Total price for out-of-state students living on campus 2014-15,Total price for in-district students living off campus,Total price for in-state students living off campus,Total price for out-of-state students living off campus,SAT Critical Reading 75th percentile score,SAT Writing 75th percentile score,SAT Math 75th percentile score,ACT Composite 75th percentile score,ACT English 75th percentile score,ACT Math 75th percentile score,ACT Writing 75th percentile score,Total men Age 25 and under,Total women Age 25 and under,Grand total Age 25 and under,Total men Age 25 and over,Total women Age 25 and over,Grand total Age 25 and over,Percent of total enrollment that are White,Percent of total enrollment that are Black or African American,Percent of total enrollment that are Hispanic/Latino,Percent of total enrollment that are Asian/Native Hawaiian/Pacific Islander,Percent of total enrollment that are American Indian or Alaska Native,Percent of total enrollment that are Race/ethnicity unknown,Percent of total enrollment that are Nonresident Alien,Percent of total enrollment that are women,Percent of total enrollment that are two or more races,Percent of total enrollment that are Asian,Percent of total enrollment that are Native Hawaiian or Other Pacific Islander,State appropriations as percent of core revenues,Local appropriations as a percent of core revenues,Academic support expenses as a percent of total core expenses,Core expenses total dollars,Core revenues total dollars,Government grants and contracts as a percent of core revenues,Institutional support expenses as a percent of total core expenses,Instruction expenses as a percent of total core expenses,Investment return as a percent of core revenues,Other core expenses as a percent of total core expenses,Other revenues as a percent of core revenues,Private gifts grants and contracts as a percent of core revenues,Public service expenses as a percent of total core expenses,Research expenses as a percent of total core expenses,Student service expenses as a percent of total core expenses,Tuition and fees as a percent of core revenues,is_FASB,is_GASB,is_forProfit
UnitID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100654,Alabama A & M University,Normal,242.0,131.0,111.0,1.0,0.0,1.0,25.0,15.0,10.0,162.0,87.0,75.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,16.0,18.0,2.0,0.0,2.0,0.0,0.0,0.0,18.0,13.0,5.0,30.0,23.0,36.0,100.0,67.0,100.0,50.0,30.0,27.0,33.0,0.0,100.0,11.0,37.0,90.0,87.0,14.0,4.0,18.0,AL,3.0,1.0,1.0,20.0,-2.0,20884.0,20884.0,28384.0,23763.0,23763.0,31263.0,470.0,470.0,470.0,19.0,19.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,91.0,1.0,1.0,0.0,1.0,1.0,55.0,0.0,0.0,0.0,30.0,0.0,6.0,1.468782e+08,1.431128e+08,30.0,11.0,22.0,0.0,29.0,6.0,2.0,9.0,9.0,14.0,33.0,0.0,1.0,0.0
100663,University of Alabama at Birmingham,Birmingham,2523.0,1441.0,1082.0,4.0,2.0,2.0,391.0,244.0,147.0,155.0,46.0,109.0,78.0,45.0,33.0,1.0,1.0,0.0,1738.0,1008.0,730.0,18.0,6.0,12.0,1.0,1.0,0.0,137.0,88.0,49.0,63.0,59.0,66.0,0.0,85.0,85.0,NaN,56.0,68.0,63.0,59.0,75.0,83.0,19.0,95.0,90.0,15.0,5.0,15.0,AL,5.0,1.0,2.0,19.0,-2.0,24405.0,24405.0,33957.0,24405.0,24405.0,33957.0,640.0,NaN,640.0,27.0,29.0,26.0,NaN,3719.0,5183.0,8902.0,1158.0,1619.0,2777.0,63.0,21.0,3.0,5.0,0.0,1.0,4.0,60.0,3.0,5.0,0.0,22.0,0.0,13.0,1.319447e+09,1.322110e+09,34.0,12.0,23.0,2.0,12.0,14.0,10.0,14.0,23.0,3.0,18.0,0.0,1.0,0.0
100690,Amridge University,Montgomery,30.0,24.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,23.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.0,NaN,33.0,NaN,NaN,NaN,NaN,0.0,NaN,50.0,NaN,NaN,NaN,33.0,100.0,100.0,6.0,5.0,20.0,AL,1.0,2.0,2.0,13.0,-2.0,NaN,NaN,NaN,19600.0,19600.0,19600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,22.0,37.0,101.0,153.0,254.0,29.0,41.0,1.0,1.0,0.0,29.0,0.0,60.0,0.0,1.0,0.0,NaN,NaN,9.0,7.286508e+06,9.710803e+06,0.0,41.0,36.0,0.0,0.0,1.0,14.0,0.0,0.0,14.0,85.0,1.0,0.0,0.0
100706,University of Alabama in Huntsville,Huntsville,363.0,196.0,167.0,1.0,1.0,0.0,62.0,47.0,15.0,20.0,8.0,12.0,8.0,5.0,3.0,0.0,0.0,0.0,253.0,125.0,128.0,1.0,0.0,1.0,0.0,0.0,0.0,18.0,10.0,8.0,58.0,55.0,61.0,50.0,65.0,65.0,NaN,43.0,33.0,61.0,31.0,82.0,60.0,25.0,94.0,89.0,12.0,4.0,16.0,AL,3.0,1.0,2.0,19.0,-2.0,23532.0,23532.0,35606.0,23532.0,23532.0,35606.0,670.0,NaN,650.0,30.0,31.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.0,11.0,3.0,4.0,1.0,3.0,6.0,43.0,1.0,4.0,0.0,22.0,0.0,5.0,2.387726e+08,2.358385e+08,43.0,9.0,30.0,0.0,8.0,3.0,2.0,3.0,35.0,9.0,29.0,0.0,1.0,0.0
100724,Alabama State University,Montgomery,226.0,114.0,112.0,0.0,0.0,0.0,29.0,21.0,8.0,138.0,58.0,80.0,3.0,3.0,0.0,0.0,0.0,0.0,51.0,31.0,20.0,0.0,0.0,0.0,5.0,1.0,4.0,0.0,0.0,0.0,33.0,27.0,37.0,50.0,20.0,25.0,0.0,31.0,53.0,47.0,41.0,25.0,63.0,36.0,95.0,89.0,14.0,3.0,19.0,AL,2.0,1.0,1.0,15.0,-2.0,18286.0,18286.0,25222.0,20812.0,20812.0,27748.0,470.0,NaN,480.0,19.0,19.0,18.0,NaN,1625.0,2606.0,4231.0,235.0,337.0,572.0,4.0,90.0,1.0,0.0,0.0,1.0,2.0,62.0,1.0,0.0,0.0,35.0,0.0,9.0,1.348889e+08,1.349931e+08,25.0,27.0,29.0,1.0,16.0,7.0,2.0,4.0,3.0,12.0,30.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492801,Drury University-College of Continuing Profess...,Springfield,8.0,2.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,2.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,5.0,18.0,NaN,0.0,0.0,NaN,0.0,0.0,13.0,0.0,NaN,NaN,NaN,92.0,84.0,-2.0,-2.0,-2.0,MO,2.0,2.0,2.0,14.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,6.920890e+06,1.257129e+07,3.0,8.0,78.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,96.0,1.0,0.0,0.0
492962,Indiana Institute of Technology-College of Pro...,Fort Wayne,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,20.0,14.0,NaN,50.0,100.0,0.0,12.0,14.0,25.0,0.0,13.0,NaN,NaN,39.0,38.0,-2.0,-2.0,-2.0,IN,2.0,2.0,2.0,14.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,3.894710e+07,4.416701e+07,36.0,30.0,33.0,10.0,11.0,1.0,3.0,0.0,0.0,21.0,51.0,1.0,0.0,0.0
494597,Faith Theological Seminary and Christian College,Tampa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,88.0,80.0,NaN,100.0,100.0,NaN,90.0,88.0,77.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494603,Southwestern Baptist Theological Seminary,Fort Worth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0,38.0,19.0,50.0,50.0,0.0,100.0,0.0,0.0,36.0,NaN,NaN,50.0,NaN,79.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494685,Urshan College,Wentzville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,33.0,23.0,NaN,NaN,NaN,NaN,NaN,0.0,31.0,NaN,0.0,100.0,NaN,19.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2.268784e+06,2.453028e+06,0.0,27.0,30.0,0.0,4.0,5.0,24.0,0.0,0.0,27.0,71.0,1.0,0.0,0.0

# Imputation Pipeline

In [82]:
#SAT scores have the highest missing value count
final_df.isna().sum().sort_values(ascending=False)

ACT Writing 75th percentile score                                                                        2020
SAT Writing 75th percentile score                                                                        1600
State appropriations as percent of core revenues                                                         1598
Local appropriations as a percent of core revenues                                                       1598
Graduation rate Native Hawaiian or Other Pacific Islander                                                1372
ACT English 75th percentile score                                                                        1240
ACT Math 75th percentile score                                                                           1238
SAT Critical Reading 75th percentile score                                                               1153
SAT Math 75th percentile score                                                                           1140
ACT Composite 75th percentile score                                                                      1096
Grand total Age 25 and over                                                                              1011
Total women Age 25 and over                                                                              1011
Total men Age 25 and over                                                                                1011
Grand total Age 25 and under                                                                             1008
Total women Age 25 and under                                                                             1008
Total men Age 25 and under                                                                               1008
Transfer-out rate total cohort                                                                            930
Graduation rate American Indian or Alaska Native                                                          910
Graduation rate Nonresident alien                                                                         743
Total price for in-district students living on campus 2014-15                                             638
Total price for out-of-state students living on campus 2014-15                                            638
Total price for in-state students living on campus 2014-15                                                638
Graduation rate Race/ethnicity unknown                                                                    623
Graduation rate two or more races                                                                         595
Graduation rate Asian                                                                                     538
Graduation rate Asian/Native Hawaiian/Other Pacific Islander                                              486
Graduation rate Black non-Hispanic                                                                        288
Graduation rate Hispanic                                                                                  240
Total price for in-state students living off campus                                                       198
Total price for out-of-state students living off campus                                                   198
Total price for in-district students living off campus                                                    198
American Indian or Alaska Native men instructional staff                                                  196
American Indian or Alaska Native women instructional staff                                                196
Asian total instructional staff                                                                           196
Asian men instructional staff                                                                             196
Asian women instructional staff                                                                           196
Black or African American total instructional staff                                                       196
Grand total women instructional staff                                                                     196
Black or African American women instructional staff                                                       196
Hispanic or Latino total instructional staff                                                              196
Hispanic or Latino men instructional staff                                                                196
American Indian or Alaska Native total instructional staff                                                196
Hispanic or Latino women instructional staff                                                              196
Race/ethnicity unknown women instructional staff                                                          196
Black or African American men instructional staff                                                         196
Race/ethnicity unknown men instructional staff                                                            196
Native Hawaiian or Other Pacific Islander total instructional staff                                       196
Native Hawaiian or Other Pacific Islander women instructional staff                                       196
White total instructional staff                                                                           196
Grand total men instructional staff                                                                       196
White men instructional staff                                                                             196
White women instructional staff                                                                           196
Two or more races total instructional staff                                                               196
Two or more races men instructional staff                                                                 196
Two or more races women instructional staff                                                               196
Grand total instructional staff                                                                           196
Race/ethnicity unknown total instructional staff                                                          196
Nonresident alien women instructional staff                                                               196
Nonresident alien men instructional staff                                                                 196
Nonresident alien total instructional staff                                                               196
Native Hawaiian or Other Pacific Islander men instructional staff                                         196
Graduation rate White non-Hispanic                                                                        111
Graduation rate women                                                                                     107
Percent of full-time first-time undergraduates awarded any financial aid                                   67
Graduation rate men                                                                                        67
Percent of full-time first-time undergraduates awarded federal state local or institutional grant aid      67
Percent of total enrollment that are White                                                                 48
Percent of total enrollment that are Black or African American                                             48
Percent of total enrollment that are Hispanic/Latino                                                       48
Percent of total enrollment that are American Indian or Alaska Native                                      48
Percent of total enrollment that are Race/ethnicity unknown                                                48
Percent of total enrollment that are Nonresident Alien                                                     48
Percent of total enrollment that are women                                                                 48
Percent of total enrollment that are two or more races                                                     48
Percent of total enrollment that are Asian                                                                 48
Percent of total enrollment that are Native Hawaiian or Other Pacific Islander                             48
Percent of total enrollment that are Asian/Native Hawaiian/Pacific Islander                                48
Student-to-faculty ratio                                                                                   28
Sector of institution                                                                                       9
Carnegie Classification 2018: Size and Setting                                                              9
Historically Black College or University                                                                    9
Institution size category                                                                                   9
State abbreviation                                                                                          9
Carnegie Classification 2018: Basic                                                                         9
Carnegie Classification 2018: Enrollment Profile                                                            9
Tuition and fees as a percent of core revenues                                                              5
Government grants and contracts as a percent of core revenues                                               5
Private gifts grants and contracts as a percent of core revenues                                            5
Other revenues as a percent of core revenues                                                                5
Investment return as a percent of core revenues                                                             5
is_FASB                                                                                                     4
Other core expenses as a percent of total core expenses                                                     4
is_GASB                                                                                                     4
Student service expenses as a percent of total core expenses                                                4
Research expenses as a percent of total core expenses                                                       4
Public service expenses as a percent of total core expenses                                                 4
is_forProfit                                                                                                4
Instruction expenses as a percent of total core expenses                                                    4
Institutional support expenses as a percent of total core expenses                                          4
Core revenues total dollars                                                                                 4
Core expenses total dollars                                                                                 4
Academic support expenses as a percent of total core expenses                                               4
Parent/child indicator - Finance                                                                            0
City location of institution                                                                                0
Graduation rate total cohort                                                                                0
Institution Name                                                                                            0
dtype: int64

In [83]:
test_scores = final_df.filter(regex='ACT|SAT').columns

We only need the school to have reported 1 of these scores to get a good idea about what the rest of the scores would be. First we will create isna columns for these values. Since  ACT Composite has the least amount of null values, we will use this to fill na values in other columns.

In [84]:
for i in test_scores:
    name = i + "_isNaN"
    final_df[name] = final_df[i].isna() * 1

ACT Scores range from 1-36 while SAT scores range from 1-800 so I will create a mapping from ACT to SAT scores using np.linspace

In [85]:
final_df.filter(regex='ACT').iloc[:, 0].unique()

array([19., 27., nan, 30., 31., 24., 29., 26., 23., 25., 22., 18., 28.,
       21., 35., 20., 34., 33., 32., 17., 16.])

In [86]:
A = np.linspace(1, 800, 37)
B = np.linspace(160, 0, 37)
C = A + B

In [87]:
act_to_sat = dict(enumerate(C))

In [88]:
# This mapping is close (not exac) to what I see online with score conversion approximations
print(f'a {28} on the ACT maps to a {act_to_sat[28]} on the SAT')
print(f'a {16} on the ACT maps to a {act_to_sat[16]} on the SAT')
print(f'a {35} on the ACT maps to a {act_to_sat[35]} on the SAT')

a 28 on the ACT maps to a 657.9999999999999 on the SAT
a 16 on the ACT maps to a 445.0 on the SAT
a 35 on the ACT maps to a 782.25 on the SAT

We are going to read in a SAT to ACT conversion chart from [The Princeton Review]("https://www.princetonreview.com/college-advice/act-to-sat-conversion")

In [124]:
ACT_SAT = pd.read_html("https://www.princetonreview.com/college-advice/act-to-sat-conversion")

In [125]:
conversion_df = ACT_SAT[0]

In [126]:
conversion_df = conversion_df.drop(["Unnamed: 2", "Unnamed: 5"], axis=1)

In [130]:
conversion_df.head(36)

     SAT  ACT  SAT.1  ACT.1  SAT.2  ACT.2
0   1600   36   1250     26    900     17
1   1590   35   1240     26    890     16
2   1580   35   1230     25    880     16
3   1570   35   1220     25    870     16
4   1560   35   1210     25    860     16
5   1550   34   1200     25    850     15
6   1540   34   1190     24    840     15
7   1530   34   1180     24    830     15
8   1520   34   1170     24    820     15
9   1510   33   1160     24    810     15
10  1500   33   1150     23    800     14
11  1490   33   1140     23    790     14
12  1480   32   1130     23    780     14
13  1470   32   1120     22    770     14
14  1460   32   1110     22    760     14
15  1450   32   1100     22    750     13
16  1440   31   1090     21    740     13
17  1430   31   1080     21    730     13
18  1420   31   1070     21    720     13
19  1410   30   1060     21    710     12
20  1400   30   1050     20    700     12
21  1390   30   1040     20    690     12
22  1380   29   1030     20    680     12
23  1370   29   1020     20    670     12
24  1360   29   1010     19    660     12
25  1350   29   1000     19    650     12
26  1340   28    990     19    640     12
27  1330   28    980     19    630     12
28  1320   28    970     18    620     11
29  1310   28    960     18    610     11
30  1300   27    950     18    600     11
31  1290   27    940     18    590     11
32  1280   27    930     17    580     11
33  1270   26    920     17    570     11
34  1260   26    910     17    560     11

In [93]:
def convert_to_act(x):
    if x < 360:
        return 12
    elif x < 380:
        return 13
    elif x < 405:
        return 14
    elif x < 430:
        return 15
    elif x < 450:
        return 16
    elif x < 470:
        return 17
    elif x < 480:
        return 18
    elif x < 510:
        return 19
    elif x < 1060:
        return 20
    elif x < 1100:
        return 21
    elif x < 1130:
        return 22
    elif x < 1160:
        return 23
    elif x < 1200:
        return: 24
    elif x < 1240:
        return 25
    elif x < 1280:
        return 26
    elif x <

In [94]:
conversion1 = conversion_df[['ACT', 'SAT']]
conversion2 = conversion_df[['ACT.1', 'SAT.1']]
conversion3 = conversion_df[['ACT.2', 'SAT.2']]

In [95]:
conversion2.columns = ['ACT', 'SAT']
conversion3.columns = ['ACT', 'SAT']

In [96]:
conversion_df = pd.concat([conversion1, conversion2, conversion3])

In [97]:
conversion_df.set_index('ACT', inplace=True)

In [98]:
groupby = conversion_df.reset_index().groupby('ACT')

In [99]:
conversion_df = groupby.agg('mean')

In [100]:
conversion_df['SAT'] = conversion_df['SAT'] / 2

In [101]:
act_sat = conversion_df['SAT'].to_dict()

In [102]:
sat_act = {v: i for i,v in act_sat.items()}

In [103]:
sat_act

{295.0: 11,
 335.0: 12,
 367.5: 13,
 390.0: 14,
 415.0: 15,
 437.5: 16,
 457.5: 17,
 477.5: 18,
 497.5: 19,
 517.5: 20,
 537.5: 21,
 555.0: 22,
 570.0: 23,
 587.5: 24,
 607.5: 25,
 627.5: 26,
 645.0: 27,
 662.5: 28,
 682.5: 29,
 700.0: 30,
 715.0: 31,
 732.5: 32,
 750.0: 33,
 767.5: 34,
 787.5: 35,
 800.0: 36}

In [104]:
act_sat

{11: 295.0,
 12: 335.0,
 13: 367.5,
 14: 390.0,
 15: 415.0,
 16: 437.5,
 17: 457.5,
 18: 477.5,
 19: 497.5,
 20: 517.5,
 21: 537.5,
 22: 555.0,
 23: 570.0,
 24: 587.5,
 25: 607.5,
 26: 627.5,
 27: 645.0,
 28: 662.5,
 29: 682.5,
 30: 700.0,
 31: 715.0,
 32: 732.5,
 33: 750.0,
 34: 767.5,
 35: 787.5,
 36: 800.0}

Now I have my conversions saved as act_sat and sat_act. If A school has either one of these values filled in we can map the rest of the scores with the following conversion dictionaries

In [105]:
(final_df.filter(regex="(SAT|ACT).*isNaN").sum(axis=1) == 7).sum()

1051

At the end we should have 1051 null values in all test score columns

In [106]:
# ACT composite has the least amount of null values with 1096
final_df.filter(regex="ACT Comp").iloc[:, 0].isna().sum()

1096

In [107]:
# first define ACT column
act_col = final_df.filter(regex="ACT Comp").columns[0]

In [108]:
# make a column of ACT to SAT score conversions
final_df["converted_act"] = final_df[act_col].fillna(0).astype(int).map(act_sat)

In [109]:
# fill SAT scores that are missing with conversions from ACT Scores
sat_math = final_df.filter(regex="SAT Math").columns[0]

In [110]:
# rename the sat_math column
final_df.rename({sat_math: "sat_math75"}, axis=1, inplace=True)

In [111]:
final_df["sat_math75"].describe() #min is 400, max is 800 after we map we will replace 0's back with NA values

count    1175.000000
mean      587.587234
std        74.016774
min       400.000000
25%       540.000000
50%       580.000000
75%       630.000000
max       800.000000
Name: sat_math75, dtype: float64

In [112]:
# find indices where math is null and but ACT Composite is not
filter1 = final_df["ACT Composite 75th percentile score_isNaN"] == 0
filter2 = final_df["SAT Math 75th percentile score_isNaN"] == 1

# save these indices as ilocs
ilocs = final_df[filter1 & filter2].index

# map the indices where SAT Math is null to the converted_act column, which are converted into sat values
final_df.loc[ilocs, "sat_math75"] = final_df.loc[ilocs, "converted_act"]

# lets view the null values in math sat scores
final_df["sat_math75"].isna().sum()

1051

In [113]:
# Lets repeat this process for reading 
filter1 = final_df["ACT Composite 75th percentile score_isNaN"] == 0
filter2 = final_df["SAT Critical Reading 75th percentile score_isNaN"] == 1

# save these indices as ilocs
ilocs = final_df[filter1 & filter2].index

# map the indices where SAT Math is null to the converted_act column, which are converted into sat values
final_df.loc[ilocs, "SAT Critical Reading 75th percentile score"] = final_df.loc[ilocs, "converted_act"]

# lets view the null values in math sat scores
final_df["SAT Critical Reading 75th percentile score"].isna().sum()

1051

In [114]:
# Lets repeat this process one more time for writing

filter1 = final_df["ACT Composite 75th percentile score_isNaN"] == 0
filter2 = final_df["SAT Writing 75th percentile score_isNaN"] == 1

# save these indices as ilocs
ilocs = final_df[filter1 & filter2].index

# map the indices where SAT Math is null to the converted_act column, which are converted into sat values
final_df.loc[ilocs, "SAT Writing 75th percentile score"] = final_df.loc[ilocs, "converted_act"]

# lets view the null values in math sat scores
final_df["SAT Writing 75th percentile score"].isna().sum()

1078

In [115]:
# Lets repeat this process one more time for writing

filter1 = final_df["SAT Critical Reading 75th percentile score_isNaN"] == 0
filter2 = final_df["SAT Writing 75th percentile score_isNaN"] == 1

# save these indices as ilocs
ilocs = final_df[filter1 & filter2].index

# map the indices where SAT Math is null to the converted_act column, which are converted into sat values
final_df.loc[ilocs, "SAT Writing 75th percentile score"] = final_df.loc[ilocs, "SAT Critical Reading 75th percentile score_isNaN"]

# lets view the null values in math sat scores
final_df["SAT Writing 75th percentile score"].isna().sum()

1051

In [116]:
final_df["converted_sat"] = final_df["SAT Critical Reading 75th percentile score"].fillna(0).astype(int).map(sat_act)

In [117]:
final_df["SAT Critical Reading 75th percentile score"].describe()
print(sat_act)

{295.0: 11, 335.0: 12, 367.5: 13, 390.0: 14, 415.0: 15, 437.5: 16, 457.5: 17, 477.5: 18, 497.5: 19, 517.5: 20, 537.5: 21, 555.0: 22, 570.0: 23, 587.5: 24, 607.5: 25, 627.5: 26, 645.0: 27, 662.5: 28, 682.5: 29, 700.0: 30, 715.0: 31, 732.5: 32, 750.0: 33, 767.5: 34, 787.5: 35, 800.0: 36}

In [118]:
# Lets repeat this process except fill for ACT scores

filter1 = ~final_df["sat_math75"].isna()
filter2 = final_df["ACT Composite 75th percentile score"].isna()

ilocs = final_df[filter1 & filter2].index


final_df.loc[ilocs, "ACT Composite 75th percentile score"] = final_df.loc[ilocs, "converted_sat"]

final_df["ACT Composite 75th percentile score"].isna().sum()

1092

In [119]:
final_df.loc[ilocs, "converted_sat"]

UnitID
139199     NaN
139630     NaN
141361     NaN
161022     NaN
161518     NaN
161873     NaN
162283     NaN
163286     NaN
163295     NaN
164155     NaN
164614     NaN
166638    23.0
167455     NaN
183062     NaN
183071     NaN
184773     NaN
184782     NaN
185129     NaN
185590     NaN
186371     NaN
186380     NaN
186399     NaN
186618     NaN
187444     NaN
190512     NaN
190549    23.0
190558     NaN
190567     NaN
190594     NaN
190600     NaN
190637     NaN
190664     NaN
190691     NaN
192925     NaN
194116     NaN
195173     NaN
199698     NaN
209825     NaN
213826     NaN
216931    23.0
233921     NaN
243106     NaN
243142    23.0
243151     NaN
243221     NaN
Name: converted_sat, dtype: float64

In [120]:
act_na = final_df.filter(regex="ACT Comp").columns[1]
sat_na = final_df.filter(regex="SAT").columns[-1]

In [121]:
len(np.where(final_df.filter(regex="SAT").iloc[:, 0].isna()))

1

In [122]:
filt1 = final_df[act_na] == 0